name: "Test run-playbook-on-ansible-tower-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        ansible-user: ${{ secrets.ansibleUser }}
        ansible-pass: ${{ secrets.ansiblePass }}
        azure-subscription: ${{ secrets.azureSubscription }}
        azure-client-id: ${{ secrets.azureClientId }}
        azure-client-secret: ${{ secrets.azureClientSecret }}
        template-id: '1254'
        additional-vars: |
          {
              "var_environment": "Development",
              "var_ctpService": "Co-Dev",
              "var_owner": "martin.calderon@gds.ey.com",
              "var_deploymentId": "TCDTCX",
              "var_chargeCode": "32405098",
              "var_location": "useast",
              "var_productApp": "INT"
          }

