name: "Test run-playbook-on-ansible-tower-action"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build

      - uses: ./
        with:
          ansible-tower-user: ${{ secrets.ansibleUser }}
          ansible-tower-pass: ${{ secrets.ansiblePass }}
          ansible-tower-url: ${{ secrets.ansibleUrl }}
          template-id: "1254"
          additional-vars: |
            {
              "var_azure_rm_subid": ${{ secrets.azureSubscription }},
              "AZURE_RM_CLIENTID": ${{ secrets.azureClientId }},
              "AZURE_RM_SECRET": ${{ secrets.azureClientSecret }}
              "var_environment": "Development",
              "var_ctpService": "Co-Dev",
              "var_owner": "martin.calderon@gds.ey.com",
              "var_deploymentId": "TCDTCX",
              "var_chargeCode": "32405098",
              "var_location": "eastus",
              "var_productApp": "INT"
            }
